import { useMemo } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { EmptyState, Header, SectionTitle, styles as ui } from "@/components/mez-ui";
import { formatDate, formatMoney, getSettlements, getTotalExpenses, useMezStore } from "@/lib/mez-store";
import { IconSymbol } from "@/components/ui/icon-symbol";

export default function HistoryScreen() {
  const router = useRouter();
  const { history, current, currency, reopenBudget } = useMezStore();
  const cards = useMemo(() => history, [history]);
  const reopen = (id: string, name: string) => Alert.alert("إعادة فتح الميز؟", `سيتم فتح «${name}» وإخفاؤه مؤقتًا من السجل.`, [{ text: "إلغاء", style: "cancel" }, { text: "إعادة فتح", onPress: () => { reopenBudget(id); router.push("/"); } }]);
  return <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={screen.content}><Header title="سجل الميز" subtitle="كل الحسابات التي أغلقتها محفوظة هنا" onBack={() => router.back()} />{current ? <View style={screen.active}><View style={screen.activeIcon}><IconSymbol name="lock" size={18} color="#2B927F" /></View><View style={screen.activeBody}><Text style={screen.activeTitle}>لديك ميز مفتوح</Text><Text style={screen.activeText}>{current.name} • يمكنك إغلاقه من شاشة التسوية</Text></View><Pressable onPress={() => router.push("/(tabs)/settlement")}><Text style={screen.activeLink}>عرض</Text></Pressable></View> : null}<SectionTitle title="الميزات السابقة" />{cards.length === 0 ? <EmptyState icon="history" title="السجل فارغ" description="بعد إغلاق أول ميز سيظهر هنا مع كل تفاصيله وحسابه النهائي." /> : cards.map((budget) => <Pressable key={budget.id} onPress={() => reopen(budget.id, budget.name)} style={({ pressed }) => [screen.card, pressed && ui.pressed]}><View style={screen.cardTop}><View style={screen.closedPill}><IconSymbol name="check" size={13} color="#2B927F" /><Text style={screen.closedText}>مغلق</Text></View><View><Text style={screen.cardTitle}>{budget.name}</Text><Text style={screen.cardDate}>{formatDate(budget.startedAt)} — {budget.closedAt ? formatDate(budget.closedAt) : ""}</Text></View></View><View style={screen.divider} /><View style={screen.metrics}><View><Text style={screen.metricLabel}>الأشخاص</Text><Text style={screen.metricValue}>{budget.people.length}</Text></View><View><Text style={screen.metricLabel}>العمليات</Text><Text style={screen.metricValue}>{budget.payments.length + budget.purchases.length}</Text></View><View><Text style={screen.metricLabel}>المصروفات</Text><Text style={screen.metricValue}>{formatMoney(getTotalExpenses(budget), currency)}</Text></View></View><View style={screen.cardBottom}><Text style={screen.openHint}>اضغط لإعادة الفتح</Text><Text style={screen.transferCount}>{getSettlements(budget).length} تحويلات مقترحة</Text></View></Pressable>)}</ScrollView></ScreenContainer>;
}
const screen = StyleSheet.create({ content: { paddingTop: 8, paddingBottom: 35 }, active: { flexDirection: "row-reverse", alignItems: "center", backgroundColor: "#EAF6F1", borderRadius: 17, padding: 12, marginBottom: 22 }, activeIcon: { width: 37, height: 37, borderRadius: 12, backgroundColor: "#D5EFE5", alignItems: "center", justifyContent: "center", marginLeft: 10 }, activeBody: { flex: 1, alignItems: "flex-end" }, activeTitle: { color: "#2B927F", fontWeight: "900", fontSize: 13 }, activeText: { color: "#49736A", fontSize: 10, marginTop: 3, textAlign: "right" }, activeLink: { color: "#2B927F", fontWeight: "900", fontSize: 12 }, card: { backgroundColor: "#FFFFFF", borderRadius: 20, borderWidth: 1, borderColor: "#E6E1D8", padding: 15, marginBottom: 11 }, cardTop: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "flex-start" }, cardTitle: { color: "#17343A", fontSize: 16, fontWeight: "900", textAlign: "right" }, cardDate: { color: "#718287", fontSize: 10, marginTop: 4, textAlign: "right" }, closedPill: { flexDirection: "row-reverse", alignItems: "center", backgroundColor: "#EAF6F1", borderRadius: 12, paddingHorizontal: 8, paddingVertical: 5, gap: 4 }, closedText: { color: "#2B927F", fontWeight: "800", fontSize: 10 }, divider: { height: 1, backgroundColor: "#EFECE6", marginVertical: 13 }, metrics: { flexDirection: "row-reverse", justifyContent: "space-between" }, metricLabel: { color: "#718287", fontSize: 10, textAlign: "right" }, metricValue: { color: "#17343A", fontSize: 13, fontWeight: "900", marginTop: 4, textAlign: "right" }, cardBottom: { flexDirection: "row-reverse", justifyContent: "space-between", marginTop: 14 }, openHint: { color: "#2B927F", fontWeight: "800", fontSize: 11 }, transferCount: { color: "#9AA6A5", fontSize: 10 } });
