import { useEffect, useMemo, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { EmptyState, Header, PrimaryButton, styles as ui } from "@/components/mez-ui";
import { PURCHASE_CATEGORIES, formatDate, formatMoney, useMezStore, type PurchaseCategory } from "@/lib/mez-store";
import { IconSymbol } from "@/components/ui/icon-symbol";

type Mode = "payment" | "purchase";
export default function OperationsScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ mode?: string }>();
  const { current, currency, addPayment, addPurchase, deletePayment, deletePurchase } = useMezStore();
  const [mode, setMode] = useState<Mode>(params.mode === "payment" ? "payment" : "purchase");
  const [showForm, setShowForm] = useState(Boolean(params.mode));
  const [personId, setPersonId] = useState("");
  const [amount, setAmount] = useState("");
  const [name, setName] = useState("");
  const [category, setCategory] = useState<PurchaseCategory>("بقالة");
  const [paidFrom, setPaidFrom] = useState<"wallet" | "personal">("personal");
  const [note, setNote] = useState("");

  useEffect(() => { if (params.mode === "payment" || params.mode === "purchase") { setMode(params.mode); setShowForm(true); } }, [params.mode]);
  const people = current?.people || [];
  const operations = useMemo(() => {
    if (!current) return [] as { id: string; type: Mode; title: string; amount: number; person: string; date: string; detail: string; from?: string }[];
    const payments = current.payments.map((item) => ({ id: item.id, type: "payment" as const, title: "دفعة إلى رصيد الميز", amount: item.amount, person: people.find((p) => p.id === item.personId)?.name || "شخص محذوف", date: item.date, detail: item.note || "دفعة" }));
    const purchases = current.purchases.map((item) => ({ id: item.id, type: "purchase" as const, title: item.name, amount: item.amount, person: people.find((p) => p.id === item.paidById)?.name || "شخص محذوف", date: item.date, detail: `${item.category} • ${item.paidFrom === "wallet" ? "من رصيد الميز" : "دفع شخصي"}`, from: item.paidFrom }));
    return [...payments, ...purchases].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }, [current, people]);

  const resetForm = () => { setAmount(""); setName(""); setNote(""); setPersonId(""); setCategory("بقالة"); setPaidFrom("personal"); };
  const save = () => {
    const value = Number(amount.replace(",", "."));
    if (!personId || !Number.isFinite(value) || value <= 0) { Alert.alert("بيانات ناقصة", "اختر الشخص واكتب مبلغًا صحيحًا."); return; }
    if (mode === "payment") addPayment({ personId, amount: value, note });
    else if (!name.trim()) { Alert.alert("اكتب اسم المشتريات", "مثل: مشتريات الأسبوع أو فاتورة المطعم."); return; }
    else addPurchase({ name: name.trim(), category, amount: value, paidById: personId, paidFrom, note });
    resetForm(); setShowForm(false);
  };
  const remove = (item: (typeof operations)[number]) => Alert.alert("حذف العملية؟", "سيتم حذفها من الحساب النهائي.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => item.type === "payment" ? deletePayment(item.id) : deletePurchase(item.id) }]);

  if (!current) return <ScreenContainer className="px-5"><Header title="العمليات" subtitle="لا يوجد ميز مفتوح" onBack={() => router.back()} /><EmptyState title="أنشئ ميزًا أولًا" description="بعد إنشاء الميز ستتمكن من تسجيل الدفعات والمشتريات." action="العودة للرئيسية" onPress={() => router.push("/")} /></ScreenContainer>;
  return (
    <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={screen.content}><Header title="العمليات" subtitle={`${operations.length} عملية مسجلة`} onBack={() => router.back()} action={<Pressable onPress={() => setShowForm(true)} style={({ pressed }) => [screen.headerAdd, pressed && ui.pressed]}><IconSymbol name="plus" size={19} color="#FFFFFF" /><Text style={screen.headerAddText}>إضافة</Text></Pressable>} />
      <View style={screen.switch}><Pressable onPress={() => setMode("purchase")} style={[screen.switchItem, mode === "purchase" && screen.switchActive]}><IconSymbol name="receipt" size={18} color={mode === "purchase" ? "#FFFFFF" : "#718287"} /><Text style={[screen.switchText, mode === "purchase" && screen.switchTextActive]}>مشتريات</Text></Pressable><Pressable onPress={() => setMode("payment")} style={[screen.switchItem, mode === "payment" && screen.switchActive]}><IconSymbol name="wallet" size={18} color={mode === "payment" ? "#FFFFFF" : "#718287"} /><Text style={[screen.switchText, mode === "payment" && screen.switchTextActive]}>دفعات</Text></Pressable></View>
      {operations.length === 0 ? <EmptyState icon="receipt" title="لا توجد عمليات بعد" description="سجّل أول دفعة أو مشتريات ليبدأ الحساب تلقائيًا." action="إضافة عملية" onPress={() => setShowForm(true)} /> : operations.map((item) => <Pressable key={`${item.type}-${item.id}`} onLongPress={() => remove(item)} style={({ pressed }) => [screen.operation, pressed && ui.pressed]}><View style={[screen.operationIcon, { backgroundColor: item.type === "payment" ? "#E3F3ED" : "#FFF0DB" }]}><IconSymbol name={item.type === "payment" ? "wallet" : "receipt"} size={20} color={item.type === "payment" ? "#2B927F" : "#C7792E"} /></View><View style={screen.operationMain}><Text style={screen.operationTitle}>{item.title}</Text><Text style={screen.operationMeta}>{item.person} • {item.detail}</Text><Text style={screen.operationDate}>{formatDate(item.date)}</Text></View><View style={screen.operationAmount}><Text style={[screen.amount, { color: item.type === "payment" ? "#2B927F" : "#C7792E" }]}>{item.type === "payment" ? "+" : "-"}{formatMoney(item.amount, currency)}</Text><Text style={screen.holdHint}>ضغط مطول للحذف</Text></View></Pressable>)}
      <View style={screen.tip}><IconSymbol name="insights" size={18} color="#2B927F" /><Text style={screen.tipText}>الدفعة تزيد رصيد الميز، أما المشتريات فتدخل في حساب المصروفات.</Text></View>
    </ScrollView>

    <Modal visible={showForm} transparent animationType="slide" onRequestClose={() => setShowForm(false)}><View style={form.overlay}><View style={form.sheet}><View style={form.handle} /><View style={form.titleRow}><Text style={form.title}>{mode === "payment" ? "إضافة دفعة" : "إضافة مشتريات"}</Text><Pressable onPress={() => { setShowForm(false); resetForm(); }}><IconSymbol name="close" size={22} color="#718287" /></Pressable></View>{mode === "purchase" ? <><Text style={form.label}>اسم المشتريات</Text><TextInput value={name} onChangeText={setName} placeholder="مثال: مشتريات الأسبوع" placeholderTextColor="#9AA6A5" style={form.input} textAlign="right" /><Text style={form.label}>التصنيف</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={form.chips}>{PURCHASE_CATEGORIES.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[form.chip, category === item && form.chipActive]}><Text style={[form.chipText, category === item && form.chipTextActive]}>{item}</Text></Pressable>)}</ScrollView></> : null}<Text style={form.label}>من الشخص؟</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={form.chips}>{people.map((person) => <Pressable key={person.id} onPress={() => setPersonId(person.id)} style={[form.personChip, personId === person.id && form.personChipActive]}><Text style={[form.personChipText, personId === person.id && form.personChipTextActive]}>{person.name}</Text></Pressable>)}</ScrollView><Text style={form.label}>المبلغ ({currency})</Text><TextInput value={amount} onChangeText={setAmount} placeholder="0.00" placeholderTextColor="#9AA6A5" style={form.amountInput} textAlign="right" keyboardType="decimal-pad" />{mode === "purchase" ? <><Text style={form.label}>طريقة الدفع</Text><View style={form.fromRow}><Pressable onPress={() => setPaidFrom("personal")} style={[form.fromOption, paidFrom === "personal" && form.fromActive]}><Text style={[form.fromText, paidFrom === "personal" && form.fromTextActive]}>دفع شخصي</Text></Pressable><Pressable onPress={() => setPaidFrom("wallet")} style={[form.fromOption, paidFrom === "wallet" && form.fromActive]}><Text style={[form.fromText, paidFrom === "wallet" && form.fromTextActive]}>من رصيد الميز</Text></Pressable></View></> : null}<Text style={form.label}>ملاحظات (اختياري)</Text><TextInput value={note} onChangeText={setNote} placeholder="أضف ملاحظة" placeholderTextColor="#9AA6A5" style={form.input} textAlign="right" /><PrimaryButton title="حفظ العملية" icon="check" onPress={save} /></View></View></Modal>
    </ScreenContainer>
  );
}
const screen = StyleSheet.create({ content: { paddingTop: 8, paddingBottom: 34 }, headerAdd: { backgroundColor: "#2B927F", borderRadius: 13, minHeight: 40, paddingHorizontal: 13, flexDirection: "row-reverse", alignItems: "center", gap: 5 }, headerAddText: { color: "#FFFFFF", fontWeight: "800", fontSize: 12 }, switch: { backgroundColor: "#EDEDEA", borderRadius: 14, padding: 4, flexDirection: "row-reverse", marginBottom: 16 }, switchItem: { flex: 1, height: 42, borderRadius: 11, flexDirection: "row-reverse", gap: 6, alignItems: "center", justifyContent: "center" }, switchActive: { backgroundColor: "#2B927F" }, switchText: { color: "#718287", fontWeight: "800", fontSize: 13 }, switchTextActive: { color: "#FFFFFF" }, operation: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E6E1D8", padding: 13, marginBottom: 9, flexDirection: "row-reverse", alignItems: "center" }, operationIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", marginLeft: 10 }, operationMain: { flex: 1, alignItems: "flex-end" }, operationTitle: { color: "#17343A", fontWeight: "800", fontSize: 14 }, operationMeta: { color: "#718287", fontSize: 11, marginTop: 4, textAlign: "right" }, operationDate: { color: "#9AA6A5", fontSize: 10, marginTop: 3 }, operationAmount: { alignItems: "flex-start", maxWidth: 112 }, amount: { fontWeight: "900", fontSize: 12, textAlign: "left" }, holdHint: { color: "#B2BCBB", fontSize: 8, marginTop: 4 }, tip: { flexDirection: "row-reverse", alignItems: "center", gap: 8, padding: 13, backgroundColor: "#EAF6F1", borderRadius: 15, marginTop: 7 }, tipText: { flex: 1, color: "#49736A", fontSize: 11, lineHeight: 18, textAlign: "right" } });
const form = StyleSheet.create({ overlay: { flex: 1, backgroundColor: "rgba(13,33,39,0.42)", justifyContent: "flex-end" }, sheet: { backgroundColor: "#F8F5EF", borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, paddingBottom: 30, maxHeight: "92%" }, handle: { width: 42, height: 4, borderRadius: 4, backgroundColor: "#D5D2CA", alignSelf: "center", marginBottom: 15 }, titleRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginBottom: 13 }, title: { color: "#17343A", fontSize: 20, fontWeight: "900", textAlign: "right" }, label: { color: "#17343A", fontWeight: "800", fontSize: 13, textAlign: "right", marginBottom: 7, marginTop: 8 }, input: { backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E6E1D8", minHeight: 47, paddingHorizontal: 14, color: "#17343A", fontSize: 14 }, amountInput: { backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#2B927F", minHeight: 55, paddingHorizontal: 16, color: "#17343A", fontSize: 22, fontWeight: "900" }, chips: { flexDirection: "row-reverse", gap: 7, paddingVertical: 3 }, chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E6E1D8" }, chipActive: { backgroundColor: "#2B927F", borderColor: "#2B927F" }, chipText: { color: "#718287", fontSize: 11, fontWeight: "700" }, chipTextActive: { color: "#FFFFFF" }, personChip: { paddingHorizontal: 15, paddingVertical: 10, borderRadius: 13, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E6E1D8" }, personChipActive: { backgroundColor: "#17343A", borderColor: "#17343A" }, personChipText: { color: "#718287", fontSize: 12, fontWeight: "800" }, personChipTextActive: { color: "#FFFFFF" }, fromRow: { flexDirection: "row-reverse", gap: 8 }, fromOption: { flex: 1, minHeight: 43, borderRadius: 12, borderWidth: 1, borderColor: "#E6E1D8", backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center" }, fromActive: { borderColor: "#2B927F", backgroundColor: "#E3F3ED" }, fromText: { color: "#718287", fontWeight: "700", fontSize: 12 }, fromTextActive: { color: "#2B927F" } });
