import { useMemo } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { EmptyState, Header, PersonCard, PrimaryButton, SectionTitle, StatCard, styles as ui } from "@/components/mez-ui";
import { formatMoney, getPersonSummaries, getSettlements, getTotalExpenses, getTotalPayments, useMezStore } from "@/lib/mez-store";
import { IconSymbol } from "@/components/ui/icon-symbol";

export default function SettlementScreen() {
  const router = useRouter();
  const { current, currency, closeBudget } = useMezStore();
  const summaries = useMemo(() => current ? getPersonSummaries(current) : [], [current]);
  const settlements = useMemo(() => current ? getSettlements(current) : [], [current]);
  const total = current ? getTotalExpenses(current) : 0;
  const close = () => Alert.alert("إغلاق الميز؟", "بعد الإغلاق سيُحفظ الميز في السجل ولن تستطيع إضافة عمليات جديدة إليه.", [{ text: "إلغاء", style: "cancel" }, { text: "إغلاق وحفظ", style: "destructive", onPress: () => { closeBudget(); router.replace("/"); } }]);
  if (!current) return <ScreenContainer className="px-5"><Header title="التسوية" subtitle="لا يوجد ميز مفتوح" onBack={() => router.back()} /><EmptyState icon="swap" title="أنشئ ميزًا أولًا" description="بعد تسجيل المصروفات سيظهر الحساب النهائي والتحويلات المقترحة." action="العودة للرئيسية" onPress={() => router.push("/")} /></ScreenContainer>;
  return <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={screen.content}><Header title="الحساب النهائي" subtitle="ملخص واضح لمن له ومن عليه" onBack={() => router.back()} /><View style={screen.summary}><Text style={screen.summaryLabel}>إجمالي مصروفات الميز</Text><Text style={screen.summaryValue}>{formatMoney(total, currency)}</Text><Text style={screen.summaryNote}>نصيب كل شخص: {formatMoney(current.people.length ? total / current.people.length : 0, currency)}</Text></View><View style={screen.stats}><StatCard compact label="المصروفات" value={formatMoney(total, currency)} icon="receipt" tone="primary" /><StatCard compact label="الدفعات" value={formatMoney(getTotalPayments(current), currency)} icon="wallet" tone="success" /></View><SectionTitle title="حالة كل شخص" />{summaries.map((person) => <PersonCard key={person.id} person={person} currency={currency} />)}<View style={screen.settleHeader}><View style={screen.settleBadge}><IconSymbol name="swap" size={18} color="#2B927F" /></View><View style={screen.settleCopy}><Text style={screen.settleTitle}>التسوية الذكية</Text><Text style={screen.settleSubtitle}>أقل عدد ممكن من التحويلات</Text></View></View>{settlements.length === 0 ? <View style={screen.equal}><IconSymbol name="check" size={23} color="#2B927F" /><Text style={screen.equalText}>كل الحسابات متساوية، لا توجد تحويلات مطلوبة.</Text></View> : settlements.map((item, index) => { const from = current.people.find((person) => person.id === item.fromId); const to = current.people.find((person) => person.id === item.toId); return <View key={`${item.fromId}-${item.toId}-${index}`} style={screen.transfer}><View style={screen.transferAmount}><Text style={screen.transferValue}>{formatMoney(item.amount, currency)}</Text><Text style={screen.transferCaption}>تحويل</Text></View><View style={screen.transferLine}><View style={screen.transferDot} /><View style={screen.line} /><View style={screen.transferDot} /></View><View style={screen.transferNames}><Text style={screen.transferFrom}>{from?.name || "شخص"}</Text><Text style={screen.transferArrow}>يدفع إلى</Text><Text style={screen.transferTo}>{to?.name || "شخص"}</Text></View></View>; })}<View style={screen.shareBox}><IconSymbol name="insights" size={19} color="#C7792E" /><Text style={screen.shareText}>يمكنك مشاركة هذه التسوية مع أصحاب الميز بعد إغلاق الحساب.</Text></View><PrimaryButton title="إغلاق الميز وحفظه" icon="lock" onPress={close} /><Pressable onPress={() => router.push("/(tabs)/operations")} style={({ pressed }) => [screen.operationsButton, pressed && ui.pressed]}><Text style={screen.operationsText}>مراجعة العمليات قبل الإغلاق</Text></Pressable></ScrollView></ScreenContainer>;
}
const screen = StyleSheet.create({ content: { paddingTop: 8, paddingBottom: 38 }, summary: { backgroundColor: "#17343A", borderRadius: 23, padding: 21, alignItems: "flex-end", marginBottom: 12 }, summaryLabel: { color: "#AFC1C0", fontSize: 12 }, summaryValue: { color: "#FFFFFF", fontSize: 29, fontWeight: "900", marginTop: 5 }, summaryNote: { color: "#B5E4D5", fontSize: 11, marginTop: 6 }, stats: { flexDirection: "row-reverse", gap: 10, marginBottom: 17 }, settleHeader: { flexDirection: "row-reverse", alignItems: "center", marginTop: 9, marginBottom: 11 }, settleBadge: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#E3F3ED", alignItems: "center", justifyContent: "center", marginLeft: 10 }, settleCopy: { alignItems: "flex-end" }, settleTitle: { color: "#17343A", fontSize: 17, fontWeight: "900" }, settleSubtitle: { color: "#718287", fontSize: 11, marginTop: 3 }, transfer: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E6E1D8", borderRadius: 18, padding: 14, marginBottom: 9, flexDirection: "row-reverse", alignItems: "center" }, transferAmount: { minWidth: 88, alignItems: "flex-start" }, transferValue: { color: "#2B927F", fontWeight: "900", fontSize: 13 }, transferCaption: { color: "#718287", fontSize: 10, marginTop: 3 }, transferLine: { flex: 1, alignItems: "center", marginHorizontal: 10 }, transferDot: { width: 8, height: 8, borderRadius: 5, backgroundColor: "#2B927F" }, line: { height: 1, width: "100%", backgroundColor: "#B5E4D5", marginVertical: 5 }, transferNames: { alignItems: "flex-end", minWidth: 93 }, transferFrom: { color: "#C7792E", fontWeight: "900", fontSize: 13 }, transferArrow: { color: "#718287", fontSize: 10, marginVertical: 2 }, transferTo: { color: "#2B927F", fontWeight: "900", fontSize: 13 }, equal: { flexDirection: "row-reverse", alignItems: "center", gap: 9, padding: 16, borderRadius: 17, backgroundColor: "#EAF6F1", marginBottom: 12 }, equalText: { color: "#49736A", flex: 1, textAlign: "right", fontSize: 12 }, shareBox: { flexDirection: "row-reverse", gap: 8, padding: 13, backgroundColor: "#FFF8EC", borderRadius: 15, marginVertical: 15 }, shareText: { color: "#8A6C41", flex: 1, fontSize: 11, lineHeight: 18, textAlign: "right" }, operationsButton: { alignItems: "center", padding: 15 }, operationsText: { color: "#2B927F", fontWeight: "800", fontSize: 13 } });
